[build]
  publish = "."

[forms]
  [forms.contact]
    name = "Contact Form"
    
[forms.contact.fields]
  name = { required = true }
  email = { required = true }
  phone = { required = true }
  location = { required = true }
  message = { required = false }
  privacy-policy = { required = true }

[forms.contact.notifications]
  [forms.contact.notifications.email]
    to = "abhiramak963@gmail.com"
    subject = "New Contact Form Submission from Tripplanner"
    template = """
    Name: {{name}}
    Email: {{email}}
    Phone: {{phone}}
    Location: {{location}}
    Message: {{message}}
    """ 