[build]
  functions = "netlify/functions"
  publish = "."

# Redirect rule to handle form submissions to Google Forms
[[redirects]]
  from = "/submit-form"
  to = "https://docs.google.com/forms/u/0/d/e/1FAIpQLSeo_Ftmc7yEY69w_TVTZcfY8RysuRY92P87xDFryUfd-uP6aQ/formResponse"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"} 